version: '2.2'

services:
  redis:
    extends:
      file: docker-compose.common.yml
      service: redis

  proxy:
    extends:
      file: docker-compose.common.yml
      service: proxy
    build: ./
    ports:
      - "127.0.0.1:5000:5000"
    entrypoint: "tail -f /dev/null"
