version: '2.2'

services:
  proxy:
    image: unocha/alpine-base-s6-python3:3.8
    volumes:
      - "./:/srv/www"
    ports:
      - "0.0.0.0:5000:5000"
    entrypoint: sleep 3600
    environment:
      # HXL_PROXY_CONFIG: /srv/www/config.py
      HXL_PROXY_CONFIG: /srv/www/docker_files/config.debug.redis.py
  
  redis:
    image: unocha/alpine-redis:5

  com:
    image: unocha/redis-commander:0.6.4
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      REDIS_HOSTS: 'local:redis:6379'
