version: '2.2'

services:
  redis:
    image: public.ecr.aws/unocha/redis:5
    hostname: redis
    container_name: hxl-proxy-redis

  proxy:
    container_name: hxl-proxy
    working_dir: /srv/www
    environment:
      HXL_PROXY_CONFIG: /srv/config/config.py
      DB_SCHEMA_FILE: schema-mysql.sql
      DB_TYPE: mysql
      MYSQL_HOST: mysql
      MYSQL_DB: hxl
      DB_PORT: 3306
      MYSQL_USER: hxl
      MYSQL_PASS: hxl
      CACHE_TYPE: redis
      CACHE_REDIS_URL: redis://redis:6379/1
