#!/usr/bin/with-contenv sh

# guard against older stacks
unset NEW_RELIC_CONFIG_FILE

[ -z "$NEW_RELIC_ENABLED"   ] && export NEW_RELIC_ENABLED=false
[ -z "$ELASTIC_APM_ENABLED" ] && export ELASTIC_APM_ENABLED=false

[ -z "$HXL_WORKERS" ]             && export HXL_WORKERS=4

if [ "$NEW_RELIC_ENABLED" == "true" ]; then
    echo "new relic is enabled."
    [ -z "$NEW_RELIC_APP_NAME"     ] && export NEW_RELIC_APP_NAME="HXL Proxy"
    [ -z "$NEW_RELIC_LICENSE_KEY"  ] && export NEW_RELIC_LICENSE_KEY="LICENSE"
    [ -z "$NEW_RELIC_LOG"          ] && export NEW_RELIC_LOG=false
    cp /srv/www/docker_files/unit-nr.json /var/lib/unit/conf.json
elif [ "$ELASTIC_APM_ENABLED" == "true" ]; then
    echo "elastic is enabled."
    [ -z "$ELASTIC_APM_SERVICE_NAME" ] && export ELASTIC_APM_SERVICE_NAME=HXL
    [ -z "$ELASTIC_APM_SERVER_URL"   ] && export ELASTIC_APM_SERVER_URL=http://localhost:8200
    [ -z "$ELASTIC_APM_SECRET_TOKEN" ] && export ELASTIC_APM_SECRET_TOKEN=
    [ -z "$ELASTIC_APM_ENVIRONMENT"  ] && export ELASTIC_APM_ENVIRONMENT=local
    cp /srv/www/docker_files/unit-elastic.json /var/lib/unit/conf.json
else
    echo "apm agents (newrelic and elastic) are disabled."
    cp /srv/www/docker_files/unit.json /var/lib/unit/conf.json
fi

chmod 600 /var/lib/unit/conf.json
chown unit /var/log/proxy

exec unitd --no-daemon --control 127.0.0.1:8080 --log /var/log/proxy/proxy.log
