#!/usr/bin/with-contenv sh

gunicorn app --chdir /srv/www -c /srv/config/gunicorn.py

[ -z "$NEW_RELIC_APP_NAME"     ] && export NEW_RELIC_APP_NAME="Python Application"
[ -z "$NEW_RELIC_CONFIG_FILE"  ] && export NEW_RELIC_CONFIG_FILE=/srv/newrelic.ini
[ -z "$NEW_RELIC_ENABLED"      ] && export NEW_RELIC_ENABLED=false
[ -z "$NEW_RELIC_LICENSE_KEY"  ] && export NEW_RELIC_LICENSE_KEY="LICENSE"
[ -z "$NEW_RELIC_LOG"          ] && export NEW_RELIC_LOG=false

[ -z "HXL_WORKERS" ]             && export HXL_WORKERS=4

if [ "$NEW_RELIC_ENABLED" = true ]; then
    echo "new relic is enabled."
    newrelic-admin generate-config $NEW_RELIC_LICENSE_KEY $NEW_RELIC_CONFIG_FILE
    exec newrelic-admin run-program gunicorn -w ${HXL_WORKERS} app --chdir /srv/www -c /srv/config/gunicorn.py
else
    echo "new relic is disabled."
    exec gunicorn -w ${HXL_WORKERS} app --chdir /srv/www -c /srv/config/gunicorn.py
fi
