name: HXL Proxy tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building HXL Proxy image
        run: docker-compose -f docker-compose-github-actions.yml build proxy
      - name: Spinning up container
        run: |
          docker-compose -f docker-compose-github-actions.yml up -d
          sleep 5
          docker-compose -f docker-compose-github-actions.yml exec -T proxy sh -c "ln -s /srv/config/schema-sqlite3.sql /srv/www/hxl_proxy/schema-sqlite3.sql"
          docker-compose -f docker-compose-github-actions.yml exec -T proxy sh -c "python3 setup.py install"
      - name: Running tests
        run: docker-compose -f docker-compose-github-actions.yml exec -T proxy sh -c "python3 setup.py test"
